name: build

on:
  workflow_dispatch:
    inputs:
      FRIDA_VERSION:
        description: 'FRIDA_VERSION'

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.event.inputs.FRIDA_VERSION }}"
          release_name: "${{ github.event.inputs.FRIDA_VERSION }}"
          draft: false
          prerelease: false

      - name: Get release UploadUrl
        id: getReleaseUploadUrl
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const releaseVersion = '${{ github.event.inputs.FRIDA_VERSION }}'
              const releaseResponse = await github.repos.getReleaseByTag({
                owner: '${{ secrets.GIT_OWNER }}',
                repo: '${{ secrets.GIT_REPO }}',
                tag: releaseVersion
              })
              const {
                data: { upload_url: uploadUrl }
              } = releaseResponse;
              core.setOutput('upload_url', uploadUrl);
            } catch (e) {
              core.setFailed(e.message);
            }

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: nttld/setup-ndk@v1.0.6
        id: setup-ndk
        with:
          ndk-version: r25b

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential tree ninja-build gcc-multilib g++-multilib lib32stdc++-9-dev flex bison xz-utils ruby ruby-dev python3-requests python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386 zip -y
          sudo gem install fpm -v 1.11.0 --no-document
          python3 -m pip install lief

      - name: repository clone
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone https://github.com/JsHookApp/Frida-Patchs Patchs
          git clone -b ${{ github.event.inputs.FRIDA_VERSION }} --recurse-submodules https://github.com/frida/frida frida
          cd frida/frida-core
          git am ../../Patchs/frida-core/*.patch

      - name: build frida for Android
        run: |
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          cd ./frida
          make core-android-arm
          make core-android-arm64
          make core-android-x86
          make core-android-x86_64

      - name: devkit frida for Android
        run: |
          cd ./frida
          python3 ./releng/devkit.py frida-gum android-arm devkit/frida-gum-arm
          python3 ./releng/devkit.py frida-gum android-arm64 devkit/frida-gum-arm64
          python3 ./releng/devkit.py frida-gum android-x86 devkit/frida-gum-x86
          python3 ./releng/devkit.py frida-gum android-x86_64 devkit/frida-gum-x86_64
          python3 ./releng/devkit.py frida-gumjs android-arm devkit/frida-gumjs-arm
          python3 ./releng/devkit.py frida-gumjs android-arm64 devkit/frida-gumjs-arm64
          python3 ./releng/devkit.py frida-gumjs android-x86 devkit/frida-gumjs-x86
          python3 ./releng/devkit.py frida-gumjs android-x86_64 devkit/frida-gumjs-x86_64
          ls ./devkit
          ls ./devkit/frida-gum-arm
          ls ./devkit/frida-gum-arm64
          ls ./devkit/frida-gum-x86
          ls ./devkit/frida-gum-x86_64
          ls ./devkit/frida-gumjs-arm
          ls ./devkit/frida-gumjs-arm64
          ls ./devkit/frida-gumjs-x86
          ls ./devkit/frida-gumjs-x86_64

      - name: zip
        run: |
          cd ${{ github.workspace }}/frida/build/frida-android-arm/bin && zip frida-server.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-arm64/bin && zip frida-server.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-x86/bin && zip frida-server.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-x86_64/bin && zip frida-server.zip *
          
          cd ${{ github.workspace }}/frida/build/frida-android-arm/lib/frida/32 && zip frida-gadget.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-arm64/lib/frida/64 && zip frida-gadget.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-x86/lib/frida/32 && zip frida-gadget.zip *
          cd ${{ github.workspace }}/frida/build/frida-android-x86_64/lib/frida/64 && zip frida-gadget.zip *
          
          cd ${{ github.workspace }}/frida/devkit/frida-gum-arm && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gum-arm64 && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gum-x86 && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gum-x86_64 && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gumjs-arm && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gumjs-arm64 && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gumjs-x86 && zip frida-devkit.zip *
          cd ${{ github.workspace }}/frida/devkit/frida-gumjs-x86_64 && zip frida-devkit.zip *

      - name: Upload android arm frida-server
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-server-${{ github.event.inputs.FRIDA_VERSION }}-android-arm.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-arm/bin/frida-server.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-server
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-server-${{ github.event.inputs.FRIDA_VERSION }}-android-arm64.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-arm64/bin/frida-server.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86 frida-server
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-server-${{ github.event.inputs.FRIDA_VERSION }}-android-x86.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-x86/bin/frida-server.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-server
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-server-${{ github.event.inputs.FRIDA_VERSION }}-android-x86_64.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-x86_64/bin/frida-server.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm frida-gadget
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gadget-${{ github.event.inputs.FRIDA_VERSION }}-android-arm.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-arm/lib/frida/32/frida-gadget.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-gadget
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gadget-${{ github.event.inputs.FRIDA_VERSION }}-android-arm64.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-arm64/lib/frida/64/frida-gadget.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86 frida-gadget
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gadget-${{ github.event.inputs.FRIDA_VERSION }}-android-x86.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-x86/lib/frida/32/frida-gadget.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-gadget
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gadget-${{ github.event.inputs.FRIDA_VERSION }}-android-x86_64.zip'
          asset_path: '${{ github.workspace }}/frida/build/frida-android-x86_64/lib/frida/64/frida-gadget.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm frida-gumjs-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gumjs-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-arm.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gumjs-arm/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-gumjs-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gumjs-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-arm64.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gumjs-arm64/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86 frida-gumjs-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gumjs-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-x86.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gumjs-x86/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-gumjs-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gumjs-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-x86_64.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gumjs-x86_64/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm frida-gum-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gum-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-arm.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gum-arm/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android arm64 frida-gum-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gum-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-arm64.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gum-arm64/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86 frida-gum-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gum-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-x86.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gum-x86/frida-devkit.zip'
          asset_content_type: application/octet-stream

      - name: Upload android x86_64 frida-gum-devkit
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ steps.getReleaseUploadUrl.outputs.upload_url }}'
          asset_name: 'frida-gum-devkit-${{ github.event.inputs.FRIDA_VERSION }}-android-x86_64.zip'
          asset_path: '${{ github.workspace }}/frida/devkit/frida-gum-x86_64/frida-devkit.zip'
          asset_content_type: application/octet-stream
